### ISSUE TITLE
開始後にEnterキーでリスタートする．

### ISSUE THREAD

**Issue by MaxMEllon** [MaxMEllon/InfoExpr2#47]
正確には，前回生成されたFieldの上に新しくfieldがaddされている．
なのでThreadがEnter長押しすると落ちる．

**Comment by MaxMEllon** [comment]
```
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException: Index: 1, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at Game.Content.Field.update(Field.java:72)
        at Game.Bong.run(Bong.java:51)
        at java.lang.Thread.run(Thread.java:745)
```
